@UserService_HostAddress = http://localhost:5293
@AccessToken = <SET_ACCESS_TOKEN>
@RefreshToken = <SET_REFRESH_TOKEN>

POST {{UserService_HostAddress}}/auth/register
Content-Type: application/json

{
  "email":"nguyentatmanh6c@gmail.com",
  "firstName": "Nguyễn",
  "lastName": "Mạnh",
  "password":"12345678",
  "phone":"0123456789"
}

###

POST {{UserService_HostAddress}}/auth/login
Content-Type: application/json

{
  "email":"tienhai2808@gmail.com",
  "password":"123456789"
}

###

POST {{UserService_HostAddress}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"{{RefreshToken}}"
}

###

GET {{UserService_HostAddress}}/auth/userinfo
Authorization: Bearer {{AccessToken}}

###

POST {{UserService_HostAddress}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "refreshToken":"{{RefreshToken}}"
}

###
