@UserService_HostAddress = http://localhost:5293

POST {{UserService_HostAddress}}/users/register
Content-Type: application/json

{
  "email":"tienhai2808@gmail.com",
  "password":"123456789",
  "fullName":"Tiến Hải",
  "phone":"0123456789"
}

###
